kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: ngrok-cluster

nodes:
- role: control-plane
  extraMounts:
    - hostPath: /dev/dri
      containerPath: /dev/dri
    - hostPath: /dev/kfd
      containerPath: /dev/kfd